# Generated by Django 5.1.1 on 2024-09-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyReport",
            fields=[
                (
                    "companyReportId",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("companyReportName", models.CharField(max_length=128)),
                ("companyReportPrice", models.IntegerField()),
                ("companyReportCategory", models.CharField(max_length=10)),
                ("content", models.TextField()),
                ("companyReportTitleImage", models.CharField(max_length=100)),
                ("regDate", models.DateTimeField(auto_now_add=True)),
                ("updDate", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "company_report",
            },
        ),
    ]
