# Generated by Django 5.1.1 on 2024-10-06 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company_report", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyDataTotal",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("company_name", models.CharField(max_length=128)),
                ("est_date", models.CharField(max_length=20, null=True)),
                ("company_class", models.CharField(max_length=20, null=True)),
                ("ceo_name", models.CharField(max_length=50, null=True)),
                ("address", models.CharField(max_length=255, null=True)),
                ("website", models.URLField(null=True)),
                ("business_summary", models.TextField(null=True)),
            ],
            options={
                "db_table": "company_data",
            },
        ),
        migrations.CreateModel(
            name="FinancialData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField()),
                ("revenue", models.BigIntegerField()),
                ("receivable_turnover", models.FloatField()),
                ("operating_cash_flow", models.BigIntegerField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company_report.companydatatotal",
                    ),
                ),
            ],
            options={
                "db_table": "company_finance",
            },
        ),
    ]
