# Generated by Django 5.1.1 on 2024-10-16 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company_report", "0002_companydatatotal_financialdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyreport",
            name="keyword",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
