# Generated by Django 5.1.1 on 2024-10-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company_report", "0003_companyreport_keyword"),
    ]

    operations = [
        migrations.RenameField(
            model_name="financialdata",
            old_name="operating_cash_flow",
            new_name="owners_capital",
        ),
        migrations.RenameField(
            model_name="financialdata",
            old_name="receivable_turnover",
            new_name="profit_trend",
        ),
        migrations.AddField(
            model_name="companydatatotal",
            name="revenue_table",
            field=models.TextField(null=True),
        ),
    ]
