# Generated by Django 5.1.1 on 2024-10-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "company_report",
            "0004_rename_operating_cash_flow_financialdata_owners_capital_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialdata",
            name="profit_trend",
            field=models.BigIntegerField(),
        ),
    ]
