# Generated by Django 5.1.1 on 2024-10-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company_report", "0005_alter_financialdata_profit_trend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyreport",
            name="companyReportTitleImage",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
