# Generated by Django 5.1.1 on 2024-10-30 01:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company_report", "0006_alter_companyreport_companyreporttitleimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyreport",
            name="companyReportCategory",
            field=models.CharField(max_length=128),
        ),
    ]
