# Generated by Django 5.1.1 on 2024-09-21 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('survey', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'survey',
            },
        ),
        migrations.CreateModel(
            name='SurveyDescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255, unique=True)),
                ('survey_id', models.OneToOneField(db_column='survey_id', on_delete=django.db.models.deletion.CASCADE, to='survey.survey')),
            ],
            options={
                'db_table': 'survey_description',
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=128, unique=True)),
                ('question_type', models.CharField(max_length=10)),
                ('essential', models.BooleanField()),
                ('survey_id', models.ForeignKey(db_column='survey_id', on_delete=django.db.models.deletion.CASCADE, to='survey.survey')),
            ],
            options={
                'db_table': 'survey_question',
            },
        ),
        migrations.CreateModel(
            name='SurveySelection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('selection', models.CharField(max_length=50, unique=True)),
                ('survey_question_id', models.ForeignKey(db_column='survey_question_id', on_delete=django.db.models.deletion.CASCADE, to='survey.surveyquestion')),
            ],
            options={
                'db_table': 'survey_selection',
            },
        ),
        migrations.CreateModel(
            name='SurveyTitle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, unique=True)),
                ('survey_id', models.ForeignKey(db_column='survey_id', on_delete=django.db.models.deletion.CASCADE, to='survey.survey')),
            ],
            options={
                'db_table': 'survey_title',
            },
        ),
    ]
