# Generated by Django 5.1.1 on 2024-09-17 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'survey',
            },
        ),
        migrations.CreateModel(
            name='SurveyDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'survey_document',
            },
        ),
        migrations.CreateModel(
            name='SurveyDescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=512, unique=True)),
                ('survey_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='survey.survey')),
            ],
            options={
                'db_table': 'survey_description',
            },
        ),
        migrations.AddField(
            model_name='survey',
            name='survey_document_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.surveydocument'),
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=128, unique=True)),
                ('survey_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey')),
            ],
            options={
                'db_table': 'survey_question',
            },
        ),
        migrations.CreateModel(
            name='SurveySelection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('selection', models.CharField(max_length=50, unique=True)),
                ('survey_question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.surveyquestion')),
            ],
            options={
                'db_table': 'survey_selection',
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('survey_question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.surveyquestion')),
                ('survey_selection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.surveyselection')),
            ],
            options={
                'db_table': 'survey_answer',
            },
        ),
        migrations.CreateModel(
            name='SurveyTitle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, unique=True)),
                ('survey_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey')),
            ],
            options={
                'db_table': 'survey_title',
            },
        ),
    ]
