# Generated by Django 5.1.1 on 2024-09-23 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=128, null=True)),
                ('account', models.ForeignKey(db_column='account_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('survey_question_id', models.ForeignKey(db_column='survey_question_id', on_delete=django.db.models.deletion.CASCADE, to='survey.surveyquestion')),
                ('survey_selection_id', models.ForeignKey(db_column='survey_selection_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.surveyselection')),
            ],
            options={
                'db_table': 'survey_answer',
            },
        ),
    ]
