# Generated by Django 5.1.1 on 2024-09-20 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_surveydescription_surveytitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='survey_id',
            new_name='survey',
        ),
    ]
