# Generated by Django 5.1.1 on 2024-09-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0002_surveyanswer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveydescription",
            name="description",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="surveyquestion",
            name="question",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="surveyselection",
            name="selection",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="surveytitle",
            name="title",
            field=models.CharField(max_length=64),
        ),
    ]
