# Generated by Django 5.1.1 on 2024-10-16 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0003_alter_surveyimage_question_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveyimage",
            name="image",
            field=models.TextField(null=True),
        ),
    ]
