# Generated by Django 5.1.1 on 2024-10-04 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('interview_id', models.IntegerField()),
            ],
            options={
                'db_table': 'interview',
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=30)),
                ('interview_id', models.ForeignKey(db_column='interview_id', on_delete=django.db.models.deletion.CASCADE, to='interview.interview')),
            ],
            options={
                'db_table': 'interview_question',
            },
        ),
    ]
