# Generated by Django 5.1.1 on 2024-11-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interview", "0004_interviewfirstquestion"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewTechQuestion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("question", models.CharField(max_length=255)),
                ("job", models.CharField(max_length=64)),
            ],
            options={
                "db_table": "interview_tech_question",
            },
        ),
    ]
